[package]
name = "bert-tui"
version.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
ratatui = { workspace = true }
thiserror.workspace = true
tui-logger = { workspace = true, features = ["tracing-support"] }
