[package]
name = "bert-bot"
version.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
bert.workspace = true
bert-base.workspace = true
libloading.workspace = true
thiserror.workspace = true
